# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

 [[main]]
   name = "💜"
   pre = "home"
   pageRef = "/"
   weight = 1


# [[main]]
#   name = "Posts"
#   pageRef = "posts"
#   weight = 10

# [[main]]
#   name = "Projects"
#   pageRef = "projects"
#   weight = 20


[[main]]
  name = "Blogs"
  pageRef = "blogs"
  weight = 10

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 10


[[main]]
  name = "About"
  pageRef = "about"
  weight = 90

# [[main]]
#   name = "Parent"
#   weight = 20

# [[main]]
#   name = "example sub-menu 1"
#   parent = "Parent"
#   pageRef = "posts"
#   weight = 20

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://twitter.com/AayanSec"
  weight = 100

[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/aayan-ta/"
  weight = 101

#[[main]]
#  identifier = "as"
#  pre = "twitter"
#  url = "https://twitter.com/AayanSec"
#  weight = 200
# https://blowfish.page/samples/icons/

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

# Tags - automatically generated based on tags placed on each article
[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


 [[footer]]
   name = "Changelog"
   pageRef = "changelog"
#   weight = 10